### ISSUE TITLE
Q: How did you get the ingame address?

### ISSUE THREAD

**Issue by Klotzi111** [Ricardonacif/launcher-abuser#1]
This project is a very clever idea to get access to the game memory.
However I wonder how you got the ingame address for the player health in Overwatch. Like one can see in the gif.
I can not read the process memory with CheatEngine to find the address. (That is what this project bypasses)
Can one tell CheatEngine to use custom RPM and WPM functions (the functions of the GameLauncherController class)?

**Comment by Ricardonacif** [comment]
Afaik there's no easy way to make cheat engine use a different method for read/write process memory. But it's open source so you could go and implement that if you want to. The player health offset I got it from reverse engineering the game, but I can't really disclose it here. I suggest going to the UC forum.
